//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11thLauncher.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_11thLauncher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arma3Sync is not configured, configure it in the settings window ähnelt.
        /// </summary>
        public static string S_A3S_DISABLED_TIP {
            get {
                return ResourceManager.GetString("S_A3S_DISABLED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to launch Arma3Sync ähnelt.
        /// </summary>
        public static string S_A3S_ENABLED_TIP {
            get {
                return ResourceManager.GetString("S_A3S_ENABLED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amber ähnelt.
        /// </summary>
        public static string S_ACCENT_AMBER {
            get {
                return ResourceManager.GetString("S_ACCENT_AMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        /// </summary>
        public static string S_ACCENT_BLUE {
            get {
                return ResourceManager.GetString("S_ACCENT_BLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brown ähnelt.
        /// </summary>
        public static string S_ACCENT_BROWN {
            get {
                return ResourceManager.GetString("S_ACCENT_BROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cobalt ähnelt.
        /// </summary>
        public static string S_ACCENT_COBALT {
            get {
                return ResourceManager.GetString("S_ACCENT_COBALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crimson ähnelt.
        /// </summary>
        public static string S_ACCENT_CRIMSON {
            get {
                return ResourceManager.GetString("S_ACCENT_CRIMSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cyan ähnelt.
        /// </summary>
        public static string S_ACCENT_CYAN {
            get {
                return ResourceManager.GetString("S_ACCENT_CYAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emerald ähnelt.
        /// </summary>
        public static string S_ACCENT_EMERALD {
            get {
                return ResourceManager.GetString("S_ACCENT_EMERALD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        public static string S_ACCENT_GREEN {
            get {
                return ResourceManager.GetString("S_ACCENT_GREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indigo ähnelt.
        /// </summary>
        public static string S_ACCENT_INDIGO {
            get {
                return ResourceManager.GetString("S_ACCENT_INDIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lime ähnelt.
        /// </summary>
        public static string S_ACCENT_LIME {
            get {
                return ResourceManager.GetString("S_ACCENT_LIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magenta ähnelt.
        /// </summary>
        public static string S_ACCENT_MAGENTA {
            get {
                return ResourceManager.GetString("S_ACCENT_MAGENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mauve ähnelt.
        /// </summary>
        public static string S_ACCENT_MAUVE {
            get {
                return ResourceManager.GetString("S_ACCENT_MAUVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Olive ähnelt.
        /// </summary>
        public static string S_ACCENT_OLIVE {
            get {
                return ResourceManager.GetString("S_ACCENT_OLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orange ähnelt.
        /// </summary>
        public static string S_ACCENT_ORANGE {
            get {
                return ResourceManager.GetString("S_ACCENT_ORANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pink ähnelt.
        /// </summary>
        public static string S_ACCENT_PINK {
            get {
                return ResourceManager.GetString("S_ACCENT_PINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purple ähnelt.
        /// </summary>
        public static string S_ACCENT_PURPLE {
            get {
                return ResourceManager.GetString("S_ACCENT_PURPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        /// </summary>
        public static string S_ACCENT_RED {
            get {
                return ResourceManager.GetString("S_ACCENT_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sienna ähnelt.
        /// </summary>
        public static string S_ACCENT_SIENNA {
            get {
                return ResourceManager.GetString("S_ACCENT_SIENNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steel ähnelt.
        /// </summary>
        public static string S_ACCENT_STEEL {
            get {
                return ResourceManager.GetString("S_ACCENT_STEEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taupe ähnelt.
        /// </summary>
        public static string S_ACCENT_TAUPE {
            get {
                return ResourceManager.GetString("S_ACCENT_TAUPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teal ähnelt.
        /// </summary>
        public static string S_ACCENT_TEAL {
            get {
                return ResourceManager.GetString("S_ACCENT_TEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Violet ähnelt.
        /// </summary>
        public static string S_ACCENT_VIOLET {
            get {
                return ResourceManager.GetString("S_ACCENT_VIOLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yellow ähnelt.
        /// </summary>
        public static string S_ACCENT_YELLOW {
            get {
                return ResourceManager.GetString("S_ACCENT_YELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking repository status ähnelt.
        /// </summary>
        public static string S_ACTION_CHECK_REPOSITORY_STATUS {
            get {
                return ResourceManager.GetString("S_ACTION_CHECK_REPOSITORY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking server status ähnelt.
        /// </summary>
        public static string S_ACTION_CHECK_SERVER_STATUS {
            get {
                return ResourceManager.GetString("S_ACTION_CHECK_SERVER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Addon presets ähnelt.
        /// </summary>
        public static string S_ADDON_PRESETS {
            get {
                return ResourceManager.GetString("S_ADDON_PRESETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About 11th MEU Launcher ähnelt.
        /// </summary>
        public static string S_APP_ABOUT {
            get {
                return ResourceManager.GetString("S_APP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 11th MEU Launcher ähnelt.
        /// </summary>
        public static string S_APP_NAME {
            get {
                return ResourceManager.GetString("S_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 11th MEU Launcher Settings ähnelt.
        /// </summary>
        public static string S_APP_SETTINGS {
            get {
                return ResourceManager.GetString("S_APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arma3Sync installation folder ähnelt.
        /// </summary>
        public static string S_BROWSE_ARMA3SYNC_FOLDER {
            get {
                return ResourceManager.GetString("S_BROWSE_ARMA3SYNC_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arma 3 game folder ähnelt.
        /// </summary>
        public static string S_BROWSE_GAME_FOLDER {
            get {
                return ResourceManager.GetString("S_BROWSE_GAME_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Java Runtime Environment folder ähnelt.
        /// </summary>
        public static string S_BROWSE_JAVA_FOLDER {
            get {
                return ResourceManager.GetString("S_BROWSE_JAVA_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string S_BTN_ABOUT {
            get {
                return ResourceManager.GetString("S_BTN_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About the launcher ähnelt.
        /// </summary>
        public static string S_BTN_ABOUT_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ABOUT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open addon website ähnelt.
        /// </summary>
        public static string S_BTN_ADDON_LINK {
            get {
                return ResourceManager.GetString("S_BTN_ADDON_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move selected item down ähnelt.
        /// </summary>
        public static string S_BTN_ADDONS_DOWN_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_DOWN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move selected item up ähnelt.
        /// </summary>
        public static string S_BTN_ADDONS_UP_TIP {
            get {
                return ResourceManager.GetString("S_BTN_ADDONS_UP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        public static string S_BTN_BROWSE {
            get {
                return ResourceManager.GetString("S_BTN_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse folder ähnelt.
        /// </summary>
        public static string S_BTN_BROWSE_ADDON {
            get {
                return ResourceManager.GetString("S_BTN_BROWSE_ADDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check server status ähnelt.
        /// </summary>
        public static string S_BTN_CHECK_SERVER_STATUS {
            get {
                return ResourceManager.GetString("S_BTN_CHECK_SERVER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to check server status ähnelt.
        /// </summary>
        public static string S_BTN_CHECK_SERVER_STATUS_TIP {
            get {
                return ResourceManager.GetString("S_BTN_CHECK_SERVER_STATUS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy launch shortcut to clipboard ähnelt.
        /// </summary>
        public static string S_BTN_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("S_BTN_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new profile ähnelt.
        /// </summary>
        public static string S_BTN_PROFILE_CREATE {
            get {
                return ResourceManager.GetString("S_BTN_PROFILE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete profile ähnelt.
        /// </summary>
        public static string S_BTN_PROFILE_DELETE {
            get {
                return ResourceManager.GetString("S_BTN_PROFILE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark as favorite ähnelt.
        /// </summary>
        public static string S_BTN_PROFILE_FAVORITE {
            get {
                return ResourceManager.GetString("S_BTN_PROFILE_FAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outdated ähnelt.
        /// </summary>
        public static string S_BTN_REPOSITORY_OUTDATED {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_OUTDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new update to the repository. Click to check again ähnelt.
        /// </summary>
        public static string S_BTN_REPOSITORY_OUTDATED_TIP {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_OUTDATED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string S_BTN_REPOSITORY_UNKNOWN {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to check the status of the repository ähnelt.
        /// </summary>
        public static string S_BTN_REPOSITORY_UNKNOWN_TIP {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UNKNOWN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updated ähnelt.
        /// </summary>
        public static string S_BTN_REPOSITORY_UPDATED {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have the latest version of the repository. Click to check again ähnelt.
        /// </summary>
        public static string S_BTN_REPOSITORY_UPDATED_TIP {
            get {
                return ResourceManager.GetString("S_BTN_REPOSITORY_UPDATED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string S_BTN_RESET_SETTINGS {
            get {
                return ResourceManager.GetString("S_BTN_RESET_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string S_BTN_SETTINGS {
            get {
                return ResourceManager.GetString("S_BTN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open settings window ähnelt.
        /// </summary>
        public static string S_BTN_SETTINGS_TIP {
            get {
                return ResourceManager.GetString("S_BTN_SETTINGS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle status ähnelt.
        /// </summary>
        public static string S_BTN_TOGGLE_ADDON {
            get {
                return ResourceManager.GetString("S_BTN_TOGGLE_ADDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string S_BTN_UPDATE {
            get {
                return ResourceManager.GetString("S_BTN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        public static string S_BTN_UPDATE_TIP {
            get {
                return ResourceManager.GetString("S_BTN_UPDATE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill server information ähnelt.
        /// </summary>
        public static string S_BUTTON_FILL_SERVER_TIP {
            get {
                return ResourceManager.GetString("S_BUTTON_FILL_SERVER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select all ähnelt.
        /// </summary>
        public static string S_BUTTON_SELECT_ALL_TIP {
            get {
                return ResourceManager.GetString("S_BUTTON_SELECT_ALL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select none ähnelt.
        /// </summary>
        public static string S_BUTTON_SELECT_NONE_TIP {
            get {
                return ResourceManager.GetString("S_BUTTON_SELECT_NONE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check repository when the application starts (requires Java and Arma3Sync configured) ähnelt.
        /// </summary>
        public static string S_CHECKBOX_CHECK_REPOSITORY {
            get {
                return ResourceManager.GetString("S_CHECKBOX_CHECK_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check servers status when the application starts ähnelt.
        /// </summary>
        public static string S_CHECKBOX_CHECK_SERVERS {
            get {
                return ResourceManager.GetString("S_CHECKBOX_CHECK_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates when the application starts ähnelt.
        /// </summary>
        public static string S_CHECKBOX_CHECK_UPDATES {
            get {
                return ResourceManager.GetString("S_CHECKBOX_CHECK_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string S_DEFAULT_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_DEFAULT_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArmA 3 ähnelt.
        /// </summary>
        public static string S_GAME_NAME {
            get {
                return ResourceManager.GetString("S_GAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style:  ähnelt.
        /// </summary>
        public static string S_LABEL_ACCENT {
            get {
                return ResourceManager.GetString("S_LABEL_ACCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string S_LABEL_ADVANCED {
            get {
                return ResourceManager.GetString("S_LABEL_ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced options ähnelt.
        /// </summary>
        public static string S_LABEL_ADVANCED_SETTINGS {
            get {
                return ResourceManager.GetString("S_LABEL_ADVANCED_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created by {0} ähnelt.
        /// </summary>
        public static string S_LABEL_APP_AUTHOR {
            get {
                return ResourceManager.GetString("S_LABEL_APP_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arma3Sync options ähnelt.
        /// </summary>
        public static string S_LABEL_ARMA3SYNC_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_ARMA3SYNC_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arma3Sync path: ähnelt.
        /// </summary>
        public static string S_LABEL_ARMA3SYNC_PATH {
            get {
                return ResourceManager.GetString("S_LABEL_ARMA3SYNC_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build {0} [{1}] - {2} ähnelt.
        /// </summary>
        public static string S_LABEL_BUILD {
            get {
                return ResourceManager.GetString("S_LABEL_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string S_LABEL_CANCEL {
            get {
                return ResourceManager.GetString("S_LABEL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game options ähnelt.
        /// </summary>
        public static string S_LABEL_GAME_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_GAME_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArmA 3 Path: ähnelt.
        /// </summary>
        public static string S_LABEL_GAME_PATH {
            get {
                return ResourceManager.GetString("S_LABEL_GAME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interface options ähnelt.
        /// </summary>
        public static string S_LABEL_INTERFACE_SETTINGS {
            get {
                return ResourceManager.GetString("S_LABEL_INTERFACE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_DETECTED {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISCLAIMER: Only select Java path if it&apos;s not automatically detected on PATH or if you want to use a different version. Compatible JRE&apos;s: 7 and 8. ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_DISCLAIMER {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Java options ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Java path: ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_PATH {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Java in PATH: ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_PATH_VAR {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_PATH_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not detected ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_UNDETECTED {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_UNDETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Java has not been detected on PATH ähnelt.
        /// </summary>
        public static string S_LABEL_JAVA_UNDETECTED_TIP {
            get {
                return ResourceManager.GetString("S_LABEL_JAVA_UNDETECTED_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string S_LABEL_LANGUAGE {
            get {
                return ResourceManager.GetString("S_LABEL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This program is distributed under GNU GPL v2 license. The program uses code from the following external libraries: ähnelt.
        /// </summary>
        public static string S_LABEL_LICENSE {
            get {
                return ResourceManager.GetString("S_LABEL_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize to notification area:  ähnelt.
        /// </summary>
        public static string S_LABEL_MINIMIZE_NOTIFICATION {
            get {
                return ResourceManager.GetString("S_LABEL_MINIMIZE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string S_LABEL_NO {
            get {
                return ResourceManager.GetString("S_LABEL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string S_LABEL_OK {
            get {
                return ResourceManager.GetString("S_LABEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List of profiles ähnelt.
        /// </summary>
        public static string S_LABEL_PROFILE_LIST {
            get {
                return ResourceManager.GetString("S_LABEL_PROFILE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile name ähnelt.
        /// </summary>
        public static string S_LABEL_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_LABEL_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repositories ähnelt.
        /// </summary>
        public static string S_LABEL_REPOSITORIES {
            get {
                return ResourceManager.GetString("S_LABEL_REPOSITORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISCLAIMER: This will delete all your parameters, settings and saved profiles. ähnelt.
        /// </summary>
        public static string S_LABEL_RESET_DISCLAIMER {
            get {
                return ResourceManager.GetString("S_LABEL_RESET_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete settings and profiles:  ähnelt.
        /// </summary>
        public static string S_LABEL_RESET_SETTINGS {
            get {
                return ResourceManager.GetString("S_LABEL_RESET_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save profile ähnelt.
        /// </summary>
        public static string S_LABEL_SAVE_PROFILE {
            get {
                return ResourceManager.GetString("S_LABEL_SAVE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER_MAP {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mission: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER_MISSION {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER_NAME {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ping: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER_PING {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Players: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER_PLAYERS {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        public static string S_LABEL_SERVER_VERSION {
            get {
                return ResourceManager.GetString("S_LABEL_SERVER_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After launching: ähnelt.
        /// </summary>
        public static string S_LABEL_START_ACTION {
            get {
                return ResourceManager.GetString("S_LABEL_START_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startup options ähnelt.
        /// </summary>
        public static string S_LABEL_STARTUP_OPTIONS {
            get {
                return ResourceManager.GetString("S_LABEL_STARTUP_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme:  ähnelt.
        /// </summary>
        public static string S_LABEL_THEME {
            get {
                return ResourceManager.GetString("S_LABEL_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string S_LABEL_YES {
            get {
                return ResourceManager.GetString("S_LABEL_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join server ähnelt.
        /// </summary>
        public static string S_LAUNCH_JOIN_SERVER {
            get {
                return ResourceManager.GetString("S_LAUNCH_JOIN_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ArmA 3 ähnelt.
        /// </summary>
        public static string S_LAUNCH_NORMAL {
            get {
                return ResourceManager.GetString("S_LAUNCH_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to restart the launcher to change language. Do you want to restart now? ähnelt.
        /// </summary>
        public static string S_MSG_CHANGE_LANGUAGE_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_CHANGE_LANGUAGE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change language ähnelt.
        /// </summary>
        public static string S_MSG_CHANGE_LANGUAGE_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_CHANGE_LANGUAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected folder does not contain a valid Arma3Sync installation ähnelt.
        /// </summary>
        public static string S_MSG_INCORRECT_ARMA3SYNC_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_ARMA3SYNC_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect path ähnelt.
        /// </summary>
        public static string S_MSG_INCORRECT_ARMA3SYNC_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_ARMA3SYNC_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected folder does not contain a valid Java Runtime Environment (JRE) ähnelt.
        /// </summary>
        public static string S_MSG_INCORRECT_JAVA_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_JAVA_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect path ähnelt.
        /// </summary>
        public static string S_MSG_INCORRECT_JAVA_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_JAVA_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected folder does not contain a valid Arma 3 installation ähnelt.
        /// </summary>
        public static string S_MSG_INCORRECT_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect path ähnelt.
        /// </summary>
        public static string S_MSG_INCORRECT_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_INCORRECT_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - The launcher has to be run with admin privileges to start ArmA 3. ähnelt.
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_ELEVATION {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_ELEVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - The ArmA 3 executable path is not defined. ähnelt.
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_PATH {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Steam has to be running to launch ArmA 3. ähnelt.
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_STEAM {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_STEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error launching ArmA 3. Check the application log for more details. ähnelt.
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_CONTENT_UNKNOWN {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_CONTENT_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to launch game ähnelt.
        /// </summary>
        public static string S_MSG_LAUNCH_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_LAUNCH_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have the latest available version of the program ähnelt.
        /// </summary>
        public static string S_MSG_NO_UPDATES_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_NO_UPDATES_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No updates available ähnelt.
        /// </summary>
        public static string S_MSG_NO_UPDATES_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_NO_UPDATES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string S_MSG_OPTION_NO {
            get {
                return ResourceManager.GetString("S_MSG_OPTION_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string S_MSG_OPTION_YES {
            get {
                return ResourceManager.GetString("S_MSG_OPTION_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The execution path has not been auto-detected, select it manually on the settings window before using the application ähnelt.
        /// </summary>
        public static string S_MSG_PATH_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_PATH_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execution path ähnelt.
        /// </summary>
        public static string S_MSG_PATH_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete all the data and existing profiles? ähnelt.
        /// </summary>
        public static string S_MSG_RESET_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_RESET_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm deletion ähnelt.
        /// </summary>
        public static string S_MSG_RESET_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_RESET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new update available. Do you want to update now? ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There has been an error checking updates. Try again later ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_ERROR_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_ERROR_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There has been an error updating the application, try again later ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_FAIL_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_FAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error updating ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_FAIL_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_FAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application has been updated successfully ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_SUCCESS_CONTENT {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_SUCCESS_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application updated ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update available ähnelt.
        /// </summary>
        public static string S_MSG_UPDATE_TITLE {
            get {
                return ResourceManager.GetString("S_MSG_UPDATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New profile name ähnelt.
        /// </summary>
        public static string S_NEW_PROFILE_NAME {
            get {
                return ResourceManager.GetString("S_NEW_PROFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional parameters ähnelt.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other parameters to use ähnelt.
        /// </summary>
        public static string S_PARAMETER_ADDITIONAL_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_ADDITIONAL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command line parameter ähnelt.
        /// </summary>
        public static string S_PARAMETER_COMMAND {
            get {
                return ResourceManager.GetString("S_PARAMETER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU Count ähnelt.
        /// </summary>
        public static string S_PARAMETER_CPU_COUNT {
            get {
                return ResourceManager.GetString("S_PARAMETER_CPU_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of CPU cores to use (equal or less than the number of processor cores) ähnelt.
        /// </summary>
        public static string S_PARAMETER_CPU_COUNT_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_CPU_COUNT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty world ähnelt.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t load any world by default ähnelt.
        /// </summary>
        public static string S_PARAMETER_EMPTY_WORLD_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_EMPTY_WORLD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of additional threads to use ähnelt.
        /// </summary>
        public static string S_PARAMETER_EX_THREADS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_EX_THREADS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extra threads ähnelt.
        /// </summary>
        public static string S_PARAMETER_EXTHREADS {
            get {
                return ResourceManager.GetString("S_PARAMETER_EXTHREADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable file patching ähnelt.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows loading of unpacked data ähnelt.
        /// </summary>
        public static string S_PARAMETER_FILE_PATCHING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_FILE_PATCHING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support for hugepages on memory ähnelt.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables hugepages support on memory ähnelt.
        /// </summary>
        public static string S_PARAMETER_HUGE_PAGES_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HUGE_PAGES_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Hyper-Threading ähnelt.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enables the use of CPU cores with Hyper-Threading ähnelt.
        /// </summary>
        public static string S_PARAMETER_HYPERTHREADING_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_HYPERTHREADING_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memory allocator - 32-bit ähnelt.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select memory allocator to use ähnelt.
        /// </summary>
        public static string S_PARAMETER_MALLOC_32_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_32_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Memory allocator - 64-bit ähnelt.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64 {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select memory allocator to use ähnelt.
        /// </summary>
        public static string S_PARAMETER_MALLOC_64_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_64_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System (Windows) ähnelt.
        /// </summary>
        public static string S_PARAMETER_MALLOC_SYSTEM {
            get {
                return ResourceManager.GetString("S_PARAMETER_MALLOC_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM memory limit ähnelt.
        /// </summary>
        public static string S_PARAMETER_MAX_MEMORY {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount of RAM memory available ähnelt.
        /// </summary>
        public static string S_PARAMETER_MAX_MEMORY_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_MEMORY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video memory limit ähnelt.
        /// </summary>
        public static string S_PARAMETER_MAX_VMEMORY {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_VMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount of video memory available ähnelt.
        /// </summary>
        public static string S_PARAMETER_MAX_VMEMORY_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_MAX_VMEMORY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No logs ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t save errors to the RPT log ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_LOGS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_LOGS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn off multicore ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disables the use of multiple cores ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_MULTICORE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_MULTICORE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No pause ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows to continue running the game when the window is not active ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_PAUSE_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_PAUSE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable splash screens ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disables the splash screens on load ähnelt.
        /// </summary>
        public static string S_PARAMETER_NO_SPLASH_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_NO_SPLASH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show script errors ähnelt.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show script errors on screen ähnelt.
        /// </summary>
        public static string S_PARAMETER_SHOW_ERRORS_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SHOW_ERRORS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Static screen on main menu ähnelt.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disables the scene on the main menu ähnelt.
        /// </summary>
        public static string S_PARAMETER_SKIP_INTRO_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_SKIP_INTRO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Force windowed mode ähnelt.
        /// </summary>
        public static string S_PARAMETER_WINDOW {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run on windowed mode ähnelt.
        /// </summary>
        public static string S_PARAMETER_WINDOW_DESC {
            get {
                return ResourceManager.GetString("S_PARAMETER_WINDOW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameters ähnelt.
        /// </summary>
        public static string S_PARAMETERS {
            get {
                return ResourceManager.GetString("S_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string S_PASSWORD {
            get {
                return ResourceManager.GetString("S_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platform ähnelt.
        /// </summary>
        public static string S_PLATFORM {
            get {
                return ResourceManager.GetString("S_PLATFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 32 bits ähnelt.
        /// </summary>
        public static string S_PLATFORM_32 {
            get {
                return ResourceManager.GetString("S_PLATFORM_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 64 bits ähnelt.
        /// </summary>
        public static string S_PLATFORM_64 {
            get {
                return ResourceManager.GetString("S_PLATFORM_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type of ArmA 3 executable to launch ähnelt.
        /// </summary>
        public static string S_PLATFORM_TIP {
            get {
                return ResourceManager.GetString("S_PLATFORM_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        public static string S_PORT {
            get {
                return ResourceManager.GetString("S_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority: ähnelt.
        /// </summary>
        public static string S_PRIORITY {
            get {
                return ResourceManager.GetString("S_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Above normal ähnelt.
        /// </summary>
        public static string S_PRIORITY_ABOVENORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_ABOVENORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High ähnelt.
        /// </summary>
        public static string S_PRIORITY_HIGH {
            get {
                return ResourceManager.GetString("S_PRIORITY_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        public static string S_PRIORITY_NORMAL {
            get {
                return ResourceManager.GetString("S_PRIORITY_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArmA 3 process priority on Windows ähnelt.
        /// </summary>
        public static string S_PRIORITY_TIP {
            get {
                return ResourceManager.GetString("S_PRIORITY_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        public static string S_PROFILES {
            get {
                return ResourceManager.GetString("S_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        public static string S_SERVER {
            get {
                return ResourceManager.GetString("S_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servers ähnelt.
        /// </summary>
        public static string S_SERVERS {
            get {
                return ResourceManager.GetString("S_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string S_SETTINGS_GENERAL {
            get {
                return ResourceManager.GetString("S_SETTINGS_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interface ähnelt.
        /// </summary>
        public static string S_SETTINGS_INTERFACE {
            get {
                return ResourceManager.GetString("S_SETTINGS_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository ähnelt.
        /// </summary>
        public static string S_SETTINGS_REPOSITORY {
            get {
                return ResourceManager.GetString("S_SETTINGS_REPOSITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close the application ähnelt.
        /// </summary>
        public static string S_START_ACTION_CLOSE {
            get {
                return ResourceManager.GetString("S_START_ACTION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize the application ähnelt.
        /// </summary>
        public static string S_START_ACTION_MINIMIZE {
            get {
                return ResourceManager.GetString("S_START_ACTION_MINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do nothing ähnelt.
        /// </summary>
        public static string S_START_ACTION_NONE {
            get {
                return ResourceManager.GetString("S_START_ACTION_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        public static string S_STATUS_READY {
            get {
                return ResourceManager.GetString("S_STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string S_THEME_DARK {
            get {
                return ResourceManager.GetString("S_THEME_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string S_THEME_LIGHT {
            get {
                return ResourceManager.GetString("S_THEME_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your ArmA 3 version ({0}) doesn&apos;t match with one or more servers ({1}) ähnelt.
        /// </summary>
        public static string S_VERSION_MISMATCH {
            get {
                return ResourceManager.GetString("S_VERSION_MISMATCH", resourceCulture);
            }
        }
    }
}
